version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tamiyochi-laravel
    volumes:
      - laravel_data:/var/www/html
    networks:
      - tamiyochi-laravel-network
    depends_on:
      - db
    ports:
      - 9000:9000

  db:
    image: mysql:5.7
    container_name: tamiyochi-mysql
    ports:
      - 3306:3306
    networks:
      - tamiyochi-laravel-network
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: pbkk
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - laravel_data:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: tamiyochi-nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - laravel_data:/var/www/html
    networks:
      - tamiyochi-laravel-network
    restart: on-failure

networks:
  tamiyochi-laravel-network:
    driver: bridge

volumes:
  laravel_data: {}
