/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    'ignition.healthCheck': [];
    'ignition.executeSolution': [];
    'ignition.updateConfig': [];
    'peminjaman.create': [];
    'peminjaman.index': [];
    'auth.register.index': [];
    'auth.login.index': [];
    'auth.register': [];
    'auth.login': [];
    'auth.logout': [];
    'seri.index': [];
    'seri.detail': [
      {
        name: 'id';
      },
    ];
    'seri.create.index': [];
    'seri.update.index': [
      {
        name: 'id';
      },
    ];
    'seri.create': [];
    'seri.genre.create': [];
    'seri.penerbit.create': [];
    'seri.penulis.create': [];
    'seri.update': [
      {
        name: 'id';
      },
    ];
    'genre.update': [
      {
        name: 'id';
      },
    ];
    'penerbit.update': [
      {
        name: 'id';
      },
    ];
    'penulis.update': [
      {
        name: 'id';
      },
    ];
    'seri.delete': [
      {
        name: 'id';
      },
    ];
    'genre.delete': [
      {
        name: 'id';
      },
    ];
    'penerbit.delete': [
      {
        name: 'id';
      },
    ];
    'penulis.delete': [
      {
        name: 'id';
      },
    ];
    'cart.index': [];
    'cart.create': [];
    'cart.delete': [
      {
        name: 'id';
      },
    ];
    'cart.delete.volume': [
      {
        name: 'id';
      },
    ];
  }
}
export {};
